#!/bin/bash

## Amy Olex
## 1/23/15
## Script to iterate through a list of bam files and perform the realignment of indels around the specified intervals


#INFILE="test_list.txt"
INTERVALS="chr22_target_intervals.list"
BAMLIST="cohort20.list"
POSTFIX="chr22"

# Save analysis ids to a list
read -d '' -r -a bamList < $BAMLIST


for bam in ${bamList[@]}
do

### Run IndelRealigner
input=$bam
output=`echo $bam.$POSTFIX.realign.bam`

if [ ! -e $output ];
then
   cmd=`echo "java -Xmx8g -Djava.io.tmpdir=/home/alolex/tmp/scratch -jar /opt/GenomeAnalysisTK-3.1/GenomeAnalysisTK.jar -I $input -R /data/refGenomes/human/GRCh37-lite/GRCh37-lite.fa -T IndelRealigner -targetIntervals $INTERVALS -o $output -known /opt/GenomeAnalysisTK-3.1/resources/Mills_and_1000G_gold_standard.indels.b37.sites.vcf"`
   echo "Executing Step 4.2 at `date` ... $cmd"
   eval $cmd
   echo "Done Step 4.2 at `date` "
else
   echo "File Found, moving to step BaseRecalibrator : $output"
fi

### Run BaseRecalibrator
input=$output
output=`echo $bam.$POSTFIX.recaldata.table`

if [ ! -e $output ];
then
   cmd=`echo "java -Xmx8g -Djava.io.tmpdir=/home/alolex/tmp/scratch -jar /opt/GenomeAnalysisTK-3.1/GenomeAnalysisTK.jar -T BaseRecalibrator -R /data/refGenomes/human/GRCh37-lite/GRCh37-lite.fa -I $input -knownSites /opt/GenomeAnalysisTK-3.1/resources/dbsnp_138.b37.vcf -knownSites /opt/GenomeAnalysisTK-3.1/resources/Mills_and_1000G_gold_standard.indels.b37.sites.vcf -o $output"`
   echo "Executing Step 5.1 at `date` ... $cmd"
   eval $cmd
   echo "Done Step 5.1 at `date` "
else
   echo "File Found, moving to step PrintReads : $output"
fi


### Run PrintReads
input_bam=`echo $bam.$POSTFIX.realign.bam`
input=$output
output=`echo $bam.$POSTFIX.recal.bam`
if [ ! -e $output ];
then
   cmd=`echo "java -Xmx8g -Djava.io.tmpdir=/home/alolex/tmp/scratch -jar /opt/GenomeAnalysisTK-3.1/GenomeAnalysisTK.jar -T PrintReads -R /data/refGenomes/human/GRCh37-lite/GRCh37-lite.fa -I $input_bam -BQSR $input -o $output"`
   echo "Executing Step 5.4 at `date` ... $cmd"
   eval $cmd
   echo "Done Step 5.4 at `date` "
else
   echo "File Found, finished realignment : $output"
fi


done

echo "FINISHED REALIGNMENT on `date`"

